spring:
  config:
    activate:
      on-profile:
        - local
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ampersand-local-bucket
      url: http://localhost:4566
      prefix: http://localhost:4566/ampersand-local-bucket/
    credentials:
      access-key: ampersand
      secret-key: ampersand
    stack:
      auto: false
