spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: user
    password: password

---
spring:
  config:
    activate:
      on-profile: local-dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AMPERSAND_DB?serverTimezone=Asia/Seoul
    username: user
    password: password

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
